CREATE TABLE IF NOT EXISTS playlists (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    you_tube_id VARCHAR(64) NOT NULL UNIQUE,
    thumbnailurl VARCHAR(1024) NOT NULL,
    etag VARCHAR(128) NOT NULL,
    curated TINYINT NOT NULL DEFAULT 0
) DEFAULT CHARSET=utf8mb4;
