# generate_js_enums.py

import argparse
import re
import sys

# Each Go block is delimited by a "// -end- <Name>" line inside a const ( ... )
# group; the group's opening line is the block's start.
# Pinning the first bit to "= 1 << iota" is what lets enumeration order stand in
# for iota: every later bare name repeats that expression, and the comment and
# blank lines dropped from the block are the ones iota does not count either.
BIT_FIRST_RE = re.compile(r'^\s*([A-Z][A-Z0-9_]*)\s+\w+\s*=\s*1\s*<<\s*iota\s*(?://.*)?$')
BIT_RE = re.compile(r'^\s*([A-Z][A-Z0-9_]*)\s*(?://.*)?$')
STRING_RE = re.compile(r'^\s*([A-Z][A-Z0-9_]*)\s*=\s*"([^"]*)"\s*(?://.*)?$')


def extract_block(path: str, name: str) -> list:
    lines = open(path).read().splitlines()
    marker = "// -end- %s" % name
    end = next((i for i, l in enumerate(lines) if l.strip() == marker), None)
    if end is None:
        sys.exit("%s: missing '%s' marker" % (path, marker))
    start = next((i for i in range(end, -1, -1) if lines[i].strip() == "const ("), None)
    if start is None:
        sys.exit("%s: no enclosing 'const (' above '%s'" % (path, marker))
    body = []
    for line in lines[start + 1:end]:
        if line.strip() and not line.strip().startswith("//"):
            body.append(line)
    return body


def parse_iota_bits(path: str, body: list) -> list:
    names = []
    for i, line in enumerate(body):
        m = (BIT_FIRST_RE if i == 0 else BIT_RE).match(line)
        if not m:
            sys.exit("%s: unparseable bit declaration: %s" % (path, line.strip()))
        names.append(m.group(1))
    return names


def parse_string_consts(path: str, body: list) -> list:
    pairs = []
    for line in body:
        m = STRING_RE.match(line)
        if not m:
            sys.exit("%s: unparseable string constant: %s" % (path, line.strip()))
        pairs.append((m.group(1), m.group(2)))
    return pairs


def render(bit_names: list, event_pairs: list, bits_src: str, events_src: str) -> str:
    s = "// GENERATED by server/code_generation/generate_js_enums.py -- do not\n"
    s += "// edit. Run `make build-api` after changing the Go source blocks:\n"
    s += "// %s (ProblemTypes), %s (EventTypes).\n" % (bits_src, events_src)
    s += "const ProblemTypes = {\n"
    for i, name in enumerate(bit_names):
        s += "  %s: Math.pow(2, %d),\n" % (name, i)
    s += "};\n\nconst EventTypes = {\n"
    for name, value in event_pairs:
        s += '  %s: "%s",\n' % (name, value)
    s += "};\n\nexport { ProblemTypes, EventTypes };\n"
    return s


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--problem-types", required=True, help="Go file holding the ProblemTypes block")
    ap.add_argument("--event-types", required=True, help="Go file holding the EventTypes block")
    ap.add_argument("-o", "--output", required=True, help="JavaScript file to write")
    args = ap.parse_args()

    bit_names = parse_iota_bits(
        args.problem_types, extract_block(args.problem_types, "ProblemTypes")
    )
    event_pairs = parse_string_consts(
        args.event_types, extract_block(args.event_types, "EventTypes")
    )
    if not bit_names or not event_pairs:
        sys.exit("refusing to write an empty enum file")

    with open(args.output, "w") as f:
        f.write(render(bit_names, event_pairs, args.problem_types, args.event_types))
    print("wrote %s: %d problem types, %d event types" % (
        args.output, len(bit_names), len(event_pairs)))


if __name__ == "__main__":
    main()
